version: "3.8"

services:
  api:
    build: .
    container_name: rt_api
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=change_me
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=notifications
    depends_on:
      - redis
      - kafka

  worker:
    build: .
    container_name: rt_worker
    command: python worker/worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=notifications
    depends_on:
      - redis
      - kafka

  redis:
    image: redis:7-alpine
    container_name: rt_redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: rt_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: rt_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1